graphql:
  protocol: http       # Протокол (не изменять)
  url: 91.185.5.210    # URL (не изменять)
  port: 3000           # Порт (не изменять)
  endpoint: /graphql   # Конечная точка (не изменять)

speedtest:
  commandString: speedtest --server-id=48175 -f json --accept-license --accept-gdpr -p   # Команда для выполнения speedtest с указанным сервером (ID 48175) и форматом json (не изменять, 48175 - ID сервера TTC speedtest001.ttc.kz)
  commandStringWin: speedtest.exe --server-id=48175 -f json --accept-license --accept-gdpr -p  # Команда для выполнения speedtest на Windows с указанным сервером (ID 48175) и форматом json (не изменять, 48175 - ID сервера TTC speedtest001.ttc.kz)
  intervalSec: 1200     # Интервал выполнения speedtest в секундах (1200 секунд = 20 минут)

global:
  client:
    station: Kumsistau        # Название станции клиента-измерителя (Изменить)
    branch: OSK          # Филиал клиента-измерителя (Изменить)
    location:
      latitude: 49.680414         # Широта местоположения клиента-измерителя (Изменить)
      longitude: 83.314745        # Долгота местоположения клиента-измерителя (Изменить)
  connection:
    type: FTTB              # Тип подключения (FTTB, ADSL, p2pVpn, GPon, WLL) (Изменить)
    login: test@test        # Логин для подключения (если p2pVpn, p2p-host@p2p) (Изменить p2p-host на IP VPn или P2P)
    vlan: 2919               # VLAN (если не используется установить как 1)
    ip: 000.000.000.000     # IP-адрес (если применимо, замените на конкретное значение xxx.xxx.xxx.xxx; если PPPoe и нет статики оставить ноли иначе указать статику)
    tp: 70               # Скорость подключения по тарифу/договору