graphql:
  protocol: http       # Протокол (не изменять в случае изменения, передавать отдельно по корпоративной почте)
  url: 91.185.5.210    # URL (не изменять в случае изменения, передавать отдельно по корпоративной почте)
  port: 3000           # Порт (не изменять в случае изменения, передавать отдельно по корпоративной почте)
  endpoint: /graphql   # Конечная точка (не изменять в случае изменения, передавать отдельно по корпоративной почте)

speedtest:
  commandString: speedtest --server-id=48175 -f json --accept-license --accept-gdpr -p   # Команда для выполнения speedtest с указанным сервером (ID 48175) и форматом json (не изменять, 48175 - ID сервера TTC speedtest001.ttc.kz)
  commandStringWin: speedtest.exe --server-id=48175 -f json --accept-license --accept-gdpr -p  # Команда для выполнения speedtest на Windows с указанным сервером (ID 48175) и форматом json (не изменять, 48175 - ID сервера TTC speedtest001.ttc.kz)
  intervalSec: 1200     # Интервал выполнения speedtest в секундах (1200 секунд = 20 минут)

global:
  client:
    station: Kumsistau   # Название станции клиента-измерителя
    branch: OSK          # Филиал клиента-измерителя
    location:
      latitude: 49.680414         # Широта местоположения клиента-измерителя 49.680414, 83.314745
      longitude: 83.314745        # Долгота местоположения клиента-измерителя
  connection:
    type: FTTB           # Тип подключения (FTTB, ADSL, p2pVpn, GPon, WLL)
    login: test@test     # Логин для подключения (если p2pVpn, оставить пустым)
    vlan: 2919           # VLAN (если применимо)
    ip: Nan              # IP-адрес (если применимо, замените на конкретное значение xxx.xxx.xxx.xxx; если PPPoe, оставить пустым)
    tp: 70               # Скорость подключения по тарифу
