version: '3.3'

services:
  client:
    build:
      context: .
    hostname: isl.osk.kumistau.ttc.kz
    container_name: isl.osk.kumistau
    environment:
      - TZ=Asia/Almaty
      - CLIENT_STATION=Kumsistau
      - CLIENT_BRANCH=OSK
      - CLIENT_LATITUDE=49.680414
      - CLIENT_LONGITUDE=83.314745
      - CONNECTION_TYPE=FTTB
      - CONNECTION_LOGIN=isit_rykovdi@osk
      - CONNECTION_VLAN=2919
      - CONNECTION_IP=000.000.000.000
      - CONNECTION_TP=70
    volumes:
      - ./docer_log:/opt/isl_client/logs
    networks:
      - default


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.200.0/24